/*
SQLyog - Free MySQL GUI v5.17
Host - 5.0.37-community-nt : Database - tpcsexam
*********************************************************************
Server version : 5.0.37-community-nt
*/

SET NAMES utf8;

SET SQL_MODE='';

create database if not exists `tpcsexam`;

USE `tpcsexam`;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO';

/*Table structure for table `admin` */

DROP TABLE IF EXISTS `admin`;

CREATE TABLE `admin` (
  `admin_id` varchar(20) NOT NULL,
  `admin_password` varchar(20) default NULL,
  PRIMARY KEY  (`admin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `admin` */

insert into `admin` (`admin_id`,`admin_password`) values ('chandan','1234');

/*Table structure for table `examinee_session` */

DROP TABLE IF EXISTS `examinee_session`;

CREATE TABLE `examinee_session` (
  `examinee_id` int(7) NOT NULL,
  `examinee_Login_start` varchar(12) NOT NULL,
  `examinee_Login_end` varchar(12) default NULL,
  `examinee_Login_total` varchar(60) default NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `examinee_session` */

/*Table structure for table `given_answer` */

DROP TABLE IF EXISTS `given_answer`;

CREATE TABLE `given_answer` (
  `examee_id` varchar(7) NOT NULL,
  `a_question_id` int(3) NOT NULL,
  `given_answer` char(1) default NULL,
  PRIMARY KEY  (`examee_id`,`a_question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `given_answer` */

/*Table structure for table `question_answer_java` */

DROP TABLE IF EXISTS `question_answer_java`;

CREATE TABLE `question_answer_java` (
  `question_id` int(3) NOT NULL,
  `option_one` varchar(50) default NULL,
  `option_two` varchar(50) default NULL,
  `option_three` varchar(50) default NULL,
  `option_four` varchar(50) default NULL,
  `question_desc` blob,
  `correct_option` varchar(1) default NULL,
  PRIMARY KEY  (`question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `question_answer_java` */

insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (1,'1, 2, 3, 4','1, 3, 4, 5','2, 4, 5, 6','3, 4, 5, 6','Which four options describe the correct default values for array elements of the types indicated? \r\n1.	int -> 0\r\n2.	String -> \"null\"\r\n3.	Dog -> null\r\n4.	char -> \'\\u0000\'\r\n5.	float -> 0.0f\r\n6.	boolean -> true\r\n','B');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (2,'class, if, void, long, Int, continue','goto, instanceof, native, finally, default, throws','try, virtual, throw, final, volatile, transient','strictfp, constant, super, implements, do','Which one of these lists contains only Java programming language keywords?','B');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (3,'int [] myList = {\"1\", \"2\", \"3\"};','int [] myList = (5, 8, 2);','int myList [] [] = {4,9,7,0};','int myList [] = {4, 3, 7};','Which will legally declare, construct, and initialize an array?','D');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (4,'method','Native','subclasses','Reference','Which is a reserved word in the Java programming language?','B');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (5,'interface','string','Float','unsigned','Which is a valid keyword in java?','A');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (6,'1, 2, 4','2, 4, 5','2, 3, 4','All are correct.','Which three are legal array declarations? 	\r\n1.	int [] myScores [];\r\n2.	char [] myChars;\r\n3.	int [6] myScores;\r\n4.	Dog myDogs [];\r\n5.	Dog myDogs [7];\r\n','A');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (7,'1, 2 and 3','2, 3 and 4','3, 4 and 5','4, 5 and 6','public interface Foo \r\n{ \r\n    int k = 4; /* Line 3 */\r\n}\r\nWhich three piece of codes are equivalent to line 3? \r\n1.	final int k = 4;\r\n2.	public int k = 4;\r\n3.	static int k = 4;\r\n4.	abstract int k = 4;\r\n5.	volatile int k = 4;\r\n6.	protected int k = 4;\r\n','A');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (8,'Array a = new Array(5);','int [] a = {23,22,21,20,19};','int a [] = new int[5];','int [5] array;','Which one of the following will declare an array and initialize it with five numbers?','B');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (9,'1, 2, 4','1, 3, 6','3, 5','5 only','Which three are valid declarations of a char? \r\n1.	char c1 = 064770;\r\n2.	char c2 = \'face\';\r\n3.	char c3 = 0xbeef;\r\n4.	char c4 = \\u0022;\r\n5.	char c5 = \'\\iface\';\r\n6.	char c6 = \'\\uface\';\r\n','B');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (10,'public double methoda();','public final double methoda();','static void methoda(double d1);','protected void methoda(double d1);','Which is the valid declarations within an interface definition?','A');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (11,'boolean b1 = 0;','boolean b2 = \'false\';','boolean b3 = false;','boolean b4 = Boolean.false();','Which one is a valid declaration of a boolean?','C');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (12,'1, 2, 4','2, 3, 5','1, 3, 6','2, 4, 6','Which three are valid declarations of a float? \r\n1.	float f1 = -343;\r\n2.	float f2 = 3.14;\r\n3.	float f3 = 0x12345;\r\n4.	float f4 = 42e7;\r\n5.	float f5 = 2001.0D;\r\n6.	float f6 = 2.81F\r\n','C');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (13,'String s1 = null;','String s2 = \'null\';','String s3 = (String) \'abc\';','String s4 = (String) \'\\ufeed\';','Which is a valid declarations of a String?','A');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (14,'-128 to 127','-(2^15) to (2^15) - 1','0 to 32767','0 to 65535','What is the numerical range of a char?','D');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (15,'Finally','Compilation fails.','The code runs with no output.','An exception is thrown at runtime.','What will be the output of the program? \r\npublic class Foo \r\n{  \r\n    public static void main(String[] args) \r\n    {\r\n        try \r\n        { \r\n            return; \r\n        } \r\n        finally \r\n        {\r\n            System.out.println( \"Finally\" ); \r\n        } \r\n    } \r\n}\r\n','A');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (16,'finished','Exception','Compilation fails.','Arithmetic Exception','What will be the output of the program? \r\ntry \r\n{ \r\n    int x = 0; \r\n    int y = 5 / x; \r\n} \r\ncatch (Exception e) \r\n{\r\n    System.out.println(\"Exception\"); \r\n} \r\ncatch (ArithmeticException ae) \r\n{\r\n    System.out.println(\" Arithmetic Exception\"); \r\n} \r\nSystem.out.println(\"finished\");\r\n','C');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (17,'ABCD','Compilation fails.','C is printed before exiting with an error message.','BC is printed before exiting with an error message','What will be the output of the program? \r\npublic class X \r\n{  \r\n    public static void main(String [] args) \r\n    {\r\n        try \r\n        {\r\n            badMethod();  \r\n            System.out.print(\"A\"); \r\n        }  \r\n        catch (Exception ex) \r\n        {\r\n            System.out.print(\"B\");  \r\n        } \r\n        finally \r\n        {\r\n            System.out.print(\"C\"); \r\n        } \r\n        System.out.print(\"D\"); \r\n    }  \r\n    public static void badMethod() \r\n    {\r\n        throw new Error(); /* Line 22 */\r\n    } \r\n}\r\n','C');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (18,'BD','BCD','BDE','BCDE','What will be the output of the program? \r\npublic class X \r\n{  \r\n    public static void main(String [] args) \r\n    {\r\n        try \r\n        {\r\n            badMethod();  \r\n            System.out.print(\"A\");  \r\n        } \r\n        catch (RuntimeException ex) /* Line 10 */\r\n        { \r\n            System.out.print(\"B\"); \r\n        } \r\n        catch (Exception ex1) \r\n        { \r\n            System.out.print(\"C\"); \r\n        } \r\n        finally \r\n        {\r\n            System.out.print(\"D\"); \r\n        } \r\n        System.out.print(\"E\"); \r\n    } \r\n    public static void badMethod() \r\n    { \r\n        throw new RuntimeException(); \r\n    } \r\n}\r\n','C');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (19,'hello throwit caught','Compilation fails','hello throwit RuntimeException caught after','hello throwit caught finally after','What will be the output of the program? \r\npublic class RTExcept \r\n{\r\n    public static void throwit () \r\n    {\r\n        System.out.print(\"throwit \");\r\n        throw new RuntimeException();\r\n    }\r\n    public static void main(String [] args) \r\n    {\r\n        try \r\n        {\r\n            System.out.print(\"hello \");\r\n            throwit();\r\n        }\r\n        catch (Exception re ) \r\n        {\r\n            System.out.print(\"caught \");\r\n        }\r\n        finally \r\n        {\r\n            System.out.print(\"finally \");\r\n        }\r\n        System.out.println(\"after \");\r\n    }\r\n}\r\n','D');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (20,'finally','exception finished','finally exception finished','Compilation fails','What will be the output of the program? \r\npublic class Test \r\n{  \r\n    public static void aMethod() throws Exception \r\n    {\r\n        try /* Line 5 */\r\n        {\r\n            throw new Exception(); /* Line 7 */\r\n        } \r\n        finally /* Line 9 */\r\n        {\r\n            System.out.print(\"finally \"); /* Line 11 */\r\n        } \r\n    } \r\n    public static void main(String args[]) \r\n    {\r\n        try \r\n        {\r\n            aMethod();  \r\n        } \r\n        catch (Exception e) /* Line 20 */\r\n        {\r\n            System.out.print(\"exception \"); \r\n        } \r\n        System.out.print(\"finished\"); /* Line 24 */\r\n    } \r\n}\r\n','C');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (21,'AC','BC','ACD','ABCD','What will be the output of the program? \r\npublic class X \r\n{ \r\n    public static void main(String [] args) \r\n    {\r\n        try \r\n        {\r\n            badMethod();  \r\n            System.out.print(\"A\"); \r\n        }  \r\n        catch (Exception ex) \r\n        {\r\n            System.out.print(\"B\"); \r\n        }  \r\n        finally \r\n        {\r\n            System.out.print(\"C\"); \r\n        }  \r\n        System.out.print(\"D\"); \r\n    }  \r\n    public static void badMethod() {} \r\n} \r\n','C');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (22,'AB','BC','ABC','BCD','What will be the output of the program? \r\npublic class X \r\n{  \r\n    public static void main(String [] args) \r\n    {\r\n        try \r\n        {\r\n            badMethod(); /* Line 7 */\r\n            System.out.print(\"A\"); \r\n        } \r\n        catch (Exception ex) /* Line 10 */\r\n        {\r\n            System.out.print(\"B\"); /* Line 12 */\r\n        } \r\n        finally /* Line 14 */\r\n        {\r\n            System.out.print(\"C\"); /* Line 16 */\r\n        }  \r\n        System.out.print(\"D\"); /* Line 18 */\r\n    } \r\n    public static void badMethod() \r\n    {\r\n        throw new RuntimeException(); \r\n    } \r\n}\r\n','D');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (23,'Nothing. The program will not compile because no e','Nothing. The program will not compile because no c','Hello world.','Hello world Finally executing','What will be the output of the program? \r\npublic class MyProgram \r\n{\r\n    public static void main(String args[])\r\n    {\r\n        try \r\n        {\r\n            System.out.print(\"Hello world \");\r\n        }\r\n        finally \r\n        {\r\n            System.out.println(\"Finally executing \");\r\n        }\r\n    }\r\n}\r\n','D');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (24,'Ex0 caught','exception caught','Compilation fails because of an error at line 2.','Compilation fails because of an error at line 9.','What will be the output of the program? \r\nclass Exc0 extends Exception { } \r\nclass Exc1 extends Exc0 { } /* Line 2 */\r\npublic class Test \r\n{  \r\n    public static void main(String args[]) \r\n    { \r\n        try \r\n        {  \r\n            throw new Exc1(); /* Line 9 */\r\n        } \r\n        catch (Exc0 e0) /* Line 11 */\r\n        {\r\n            System.out.println(\"Ex0 caught\"); \r\n        } \r\n        catch (Exception e) \r\n        {\r\n            System.out.println(\"exception caught\");  \r\n        } \r\n    } \r\n}\r\n','A');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (25,'public','private','protected','transient','You want subclasses in any package to have access to members of a superclass. \r\nWhich is the most restrictive access that accomplishes this objective?','C');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (26,'new Inner(); //At line 5','new Inner(); //At line 10','new ot.Inner(); //At line 10','new Outer.Inner(); //At line 10','public class Outer \r\n{ \r\n    public void someOuterMethod() \r\n    {\r\n        //Line 5 \r\n    } \r\n    public class Inner { } \r\n    \r\n    public static void main(String[] argv) \r\n    {\r\n        Outer ot = new Outer(); \r\n        //Line 10\r\n    } \r\n} \r\nWhich of the following code fragments inserted, will allow to compile?\r\n','A');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (27,'1 and 2','2 and 3','3 and 4','1 and 5','interface Base \r\n{\r\n    boolean m1 ();\r\n    byte m2(short s);\r\n}\r\nwhich two code fragments will compile? \r\n1.	interface Base2 implements Base {}\r\n2.	abstract class Class2 extends Base \r\n{ public boolean m1(){ return true; }} \r\n3.	abstract class Class2 implements Base {}\r\n4.	abstract class Class2 implements Base \r\n{ public boolean m1(){ return (7 > 4); }}\r\n5.	abstract class Class2 implements Base \r\n{ protected boolean m1(){ return (5 > 7) }}\r\n','C');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (28,'1, 3, 4','2, 4, 5','1, 2, 6','2, 5, 6','Which three form part of correct array declarations? \r\n1.	public int a [ ]\r\n2.	static int [ ] a\r\n3.	public [ ] int a\r\n4.	private int a [3]\r\n5.	private int [3] a [ ]\r\n6.	public final int [ ] a\r\n','C');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (29,'Test( )','Test(void)','public Test( )','public Test(void)','public class Test { }\r\nWhat is the prototype of the default constructor?\r\n','C');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (30,'public','abstract','synchronized','default access','What is the most restrictive access modifier that will allow\r\n members of one class to have access to members of another class in the same package?','D');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (31,'1 and 3','2 and 4','1 only','All of them are legal declarations','Which of the following is/are legal method declarations? \r\n1.	protected abstract void m1();\r\n2.	static final void m1(){}\r\n3.	synchronized public final void m1() {}\r\n4.	private native void m1();\r\n','D');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (32,'int[ ] scores = {3, 5, 7};','int [ ][ ] scores = {2,7,6}, {9,3,45};','String cats[ ] = {\"Fluffy\", \"Spot\", \"Zeus\"};','boolean results[ ] = new boolean [] {true, false, ','Which cause a compiler error?','B');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (33,'1 and 2','2, 3 and 5','3, 4, and 5','2 and 4','Which three are valid method signatures in an interface? \r\n1.	private int getArea();\r\n2.	public float getVol(float x);\r\n3.	public void main(String [] args);\r\n4.	public static void main(String [] args);\r\n5.	boolean setFlag(Boolean [] test);\r\n','B');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (34,'public','private','protected','default access','You want a class to have access to members of another class in the same package. \r\nWhich is the most restrictive access that accomplishes this objective?','D');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (35,'int','byte','long','double','What is the narrowest valid returnType for methodA in line 3? \r\npublic class ReturnIt \r\n{ \r\n    returnType methodA(byte x, double y) /* Line 3 */\r\n    { \r\n        return (long)x / y * 2; \r\n    } \r\n}\r\n','D');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (36,'public int method1(int a, int b) {return 0; }','private int method1(int a, int b) { return 0; }','public short method1(int a, int b) { return 0; }','static protected int method1(int a, int b) { retur','class A \r\n{  \r\n    protected int method1(int a, int b) \r\n    {\r\n        return 0; \r\n    } 			\r\n}\r\nWhich is valid in a class that extends class A?\r\n','A');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (37,'int[ ] ia = new int[15];','float fa = new float[20];','char[ ] ca = \"Some String\";','int ia[ ] [ ] = { 4, 5, 6 }, { 1,2,3 };','Which one creates an instance of an array?','A');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (38,'1 and 4','2 and 5','3 and 6','4 and 6','Which two of the following are legal declarations for nonnested classes and interfaces? \r\n1.	final abstract class Test {}\r\n2.	public static interface Test {}\r\n3.	final public class Test {}\r\n4.	protected abstract class Test {}\r\n5.	protected interface Test {}\r\n6.	abstract public class Test {}\r\n','C');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (39,'protected int a;','transient int b = 3;','private synchronized int e;','volatile int d;','Which of the following class level (nonlocal) variable declarations will not compile?','C');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (40,'2, 4','3, 5','4, 5','1, 2','Which two cause a compiler error? \r\n1.	float[ ] f = new float(3);\r\n2.	float f2[ ] = new float[ ];\r\n3.	float[ ]f1 = new float[3];\r\n4.	float f3[ ] = new float[3];\r\n5.	float f5[ ] = {1.0f, 2.0f, 2.0f};\r\n','D');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (41,'final','static','private','protected','Given a method in a protected class, \r\nwhat access modifier do you use to restrict access to that method to only the other members of the same class?','C');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (42,'public static short stop = 23;','protected short stop = 23;','transient short stop = 23;','final void madness(short stop);','Which is a valid declaration within an interface?','A');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (43,'12 15','15 15','3 4 5 3 7 5','3 7 5 3 7 5','What will be the output of the program? \r\nclass PassA \r\n{\r\n    public static void main(String [] args) \r\n    {\r\n        PassA p = new PassA();\r\n        p.start();\r\n    }\r\n\r\n    void start() \r\n    {\r\n        long [] a1 = {3,4,5};\r\n        long [] a2 = fix(a1);\r\n        System.out.println(a1[0] + a1[1] + a1[2] + \" \");\r\n        System.out.println(a2[0] + a2[1] + a2[2]);\r\n    }\r\n\r\n    long [] fix(long [] a3) \r\n    {\r\n        a3[1] = 7;\r\n        return a3;\r\n    }\r\n}\r\n','B');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (44,'true true','false true','true false','false false','What will be the output of the program? \r\nclass Test \r\n{\r\n    public static void main(String [] args) \r\n    {\r\n        Test p = new Test();\r\n        p.start();\r\n    }\r\n\r\n    void start() \r\n    {\r\n        boolean b1 = false;\r\n        boolean b2 = fix(b1);\r\n        System.out.println(b1 + \" \" + b2);\r\n    }\r\n\r\n    boolean fix(boolean b1) \r\n    {\r\n        b1 = true;\r\n        return b1;\r\n    }\r\n}\r\n','B');
insert into `question_answer_java` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (45,'slip stream','slipstream stream','stream slip stream','slipstream slip stream','What will be the output of the program? \r\nclass PassS \r\n{\r\n    public static void main(String [] args) \r\n    {\r\n        PassS p = new PassS();\r\n        p.start();\r\n    }\r\n\r\n    void start() \r\n    {\r\n        String s1 = \"slip\";\r\n        String s2 = fix(s1);\r\n        System.out.println(s1 + \" \" + s2);\r\n    }\r\n\r\n    String fix(String s1) \r\n    {\r\n        s1 = s1 + \"stream\";\r\n        System.out.println(s1 + \" \");\r\n        return \"stream\";\r\n    }\r\n}\r\n','D');

/*Table structure for table `question_answer_net` */

DROP TABLE IF EXISTS `question_answer_net`;

CREATE TABLE `question_answer_net` (
  `question_id` int(3) NOT NULL,
  `option_one` varchar(50) default NULL,
  `option_two` varchar(50) default NULL,
  `option_three` varchar(50) default NULL,
  `option_four` varchar(50) default NULL,
  `question_desc` blob,
  `correct_option` varchar(1) default NULL,
  PRIMARY KEY  (`question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `question_answer_net` */

insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (1,'VB.NET','VB 6','C++','C#','Which language is not a true object-oriented programming language?','B');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (2,'properties','methods','events','All of the above','An object is composed of:                                 ','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (3,'One object is used to create one class.','One class is used to create one object','One object can create many classes.','One class can create many objects.','Which statement about objects is true?','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (4,'contains over 25,000 classes.','uses namespaces to manage all of the classes','has the System.Form namespace for classes used in ','Both a and b','The .Net class library:','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (5,'Hide','Show','Visible','Cursor','Which property determines whether a control is displayed to the user?','C');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (6,'programmatically through the click event','by clicking the button with the mouse.','with the form‚Äôs DefaultButton property','Both a and b','The Button control can be activated','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (7,'the system.','a user‚Äôs action.','the program itself.','All of the above','In event-driven programming an event is generated by:                                 ','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (8,'Click','SingleClick','DoubleClick','MouseMove','Which is not a common control event?','B');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (9,'Form','Button ','TextBox','Timer','The Tick event is found only in which object?','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (10,'Analysis','Design','Implementation','Maintenance','Which phase of project development typically costs the most?','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (11,'Floating point','Integer','Boolean','Both a and b.','Which is a numeric data type?','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (12,'is unsigned','has two states.','is displayed by the program as yes or no.','Both a and b.','The Boolean data type:','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (13,'logical, comparison, and arithmetic.','arithmetic, comparison, and logical.','arithmetic, logical, and comparison.','comparison, arithmetic, and logical.','The proper operator precedence, from first to last, is: ','B');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (14,'NOT','AND','XOR','OR','Which operator is evaluated first?','A');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (15,'cause an error.','cannot be done.','de-select any selected item.','Both a and b.','Setting the SelectedIndex property of a ListBox to -1 will:','C');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (16,'Items.RemoveAt','Item.RemoveAt','Items.ClearAt','Item.ClearAt','Which method of a ListBox will remove just one item at a time?','A');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (17,'in all If‚Ä¶Then statements.','in all Multi-line statements with Else.','in Single Line statements.','Both a and b.','The End If statement is required:','B');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (18,'If‚Ä¶Then','Select Case','Do‚Ä¶Loop','For‚Ä¶Next','Which selection process is an example of multiple branches from a single expression? ','B');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (19,'Do While Score > 100','Do Until Score > 100','Loop While Score > 100','Loop Until Score > 100','Which DoÖLoop statement should be used to process test scores where a test score over 100 is a signal to stop the processing?','B');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (20,'IsArithmetic','IsNotString','IsNumeric','IsString','Which function should be used to validate that input is not a string before performing arithmetic operations?','C');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (21,'Dividing by zero.','Assigning the string ‚ÄúHi‚Äù to an integer variable','Accessing an empty CD drive.','All of the above..','Which action will raise an exception?','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (22,'0','1','2','3','How many RadioButtons in a Group Box can be selected at the same time?','B');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (23,'Close','Copy','Exit','Print','Which menu item is not typically found in the File Menu?','B');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (24,'Every table should have a primary key.','A primary key exclusively identifies each row in a','A primary key can be made of multiple fields.','All of the above. ','Which is true about the primary key?','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (25,'JOIN','ON','ORDER BY','SELECT','Which clause is required in an SQL query for getting information from a database?','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (26,'fields','records','tables','All of the above','The ORDER BY clause is used to sort:','B');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (27,'Location','Type','Query','Both a and b.','Which property of the database must the connection object contain?','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (28,'an adapter object','a connection object.','a database object.','a dataset object.','The first step of configuring a DataAdapter is to select: ','B');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (29,'Dataset','DataAdapter','Connection','All of the above.','Which object does the data-aware control bind to?','A');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (30,'DataMember','DataSource','DataQuery','Both a and b.','Which is a property of the DataGrid control?','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (31,'B','center','HR','I','Which HTML tag does not use an end tag?','C');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (32,'A href','A ref','An href','An ref','Which HTML tag creates a link to another browser page?','A');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (33,'a browser posts a form to the server.','a user‚Äôs action activates the handing of a server ','a server posts a form to the client.','All of the above. ','A postback occurs when:','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (34,' all ASP.NET code.','as much ASP.NET code as is in the ASP.NET file.','a mix of ASP.NET and HTML code.','all HTML code.','When an ASP.NET file is placed on an IIS server and viewed through a browser, the resulting HTML page contains:','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (35,'Application ','Association ','Data ','Logical ','Which layer is exemplified by a web server in three tier architecture? ','A');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (36,'on a web server.','without information from a database.','without knowledge of previous web pages','before a request from a client.','The stateless HTTP protocol refers to web pages created:','C');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (37,'Cookies','Query string','View state','All of the above. ','Which client-side technique is specific to ASP.NET?','C');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (38,'Application states','Session states','Database support','All of the above. ','Which server-side technique is available in ASP.NET?','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (39,'10 minutes','20 minutes','60 minutes','100 minutes','If there is no activity from a browser, how long will a session variable last?','B');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (40,'a simple answer to the complex problem of creating','an incremental improvement to the problem of creat','the way to get rid of a werewolf.','All of the above. ','We should think of the practice of object-oriented programming as:                                 ','B');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (41,'reuse and modify existing modules of code','write and read code by sharing method names','hide and protect data from external code.','All of the above. ','Encapsulation makes it easier to:','C');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (42,'A base class inherits some of the properties of a ','A base class inherits all of the properties of a d','A derived class inherits some of the properties of','A derived class inherits all of the properties of ','Which statement is true?','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (43,'It works as a stand-alone Web-development tool.','It works the same with all Web browsers.','It uses C++ as its programming language','It makes data requests asynchronously.','What makes Ajax unique?','D');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (44,' SELECT COLUMNS(*) FROM Persons',' SELECT COUNT() FROM Persons','SELECT COUNT(*) FROM Persons','SELECT COLUMNS() FROM Persons','With SQL, how can you return the number of records in the ìPersonsî table?','C');
insert into `question_answer_net` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (45,'Boolean','int','object','string','____________ is the DataType return in ìIsPostbackî property','A');

/*Table structure for table `question_answer_php` */

DROP TABLE IF EXISTS `question_answer_php`;

CREATE TABLE `question_answer_php` (
  `question_id` int(3) NOT NULL,
  `option_one` varchar(50) default NULL,
  `option_two` varchar(50) default NULL,
  `option_three` varchar(50) default NULL,
  `option_four` varchar(50) default NULL,
  `question_desc` blob,
  `correct_option` varchar(1) default NULL,
  PRIMARY KEY  (`question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `question_answer_php` */

insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (1,'mysqlconnect() function','mysql-connect() function','mysql_connect() function','sql_connect() function','In PHP in order to access MySQL database you will use:\r\n','B');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (2,'It converts them to a common compatible data type ','It returns True only if they are both of the same ','If the two values are strings, it performs a lexic','It bases its comparison on the C strcmp function e','How does the identity operator === compare two values?','A');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (3,'Pond-sign','Yen-sign','Dollar-sign','Euro-sign','Variables always start with a ........ In PHP','C');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (4,'25','-5','10','5','What is the value displayed when the following is executed? Assume that the code was executed using the following URL:\r\n\r\ntestscript.php?c=25\r\n\r\n<?php\r\nfunction process($c, $d = 25)\r\n{\r\nglobal $e;\r\n$retval = $c + $d - $_GET[\'c\'] - $e;\r\nreturn $retval;\r\n}\r\n$e = 10;\r\necho process(5);\r\n?>\r\n','B');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (5,'$_10','${‚ÄúMyVar‚Äù}','&$something','$10_somethings','Which of the following is not valid PHP code?','D');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (6,' print() can be used as part of an expression, whi','echo() can be used as part of an expression, while','echo() can be used in the CLI version of PHP, whil',' print() can be used in the CLI version of PHP, wh','What is the difference between print() and echo()?','A');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (7,' $s1 + $s2',' \"{$s1}{$s2}\"','$s1.$s2','implode(\' \', array($s1,$s2))','Which of the following will not combine strings $s1 and $s2 into a single string?','A');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (8,'substr($email, strpos($email, \"@\"));','strstr($email, \"@\");','strchr($email, \"@\");','substr($email, strpos($email, \"@\")+1);','Given a variable $email containing the string user@example.com, which of the following statements would extract the string example.com?\r\n','D');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (9,'strstr()',' Cannot be done with a single function',' extract()','explode()','Given a comma-separated list of values in a string, which function from the given list can create an array of each individual value with a single call?','D');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (10,' Using the strpos function',' Using the == operator','Using strcasecmp()','Using strcmp()','What is the best all-purpose way of comparing two strings?\r\n','D');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (11,'.*','[a-z][a-z][a-z]\\|\\w{9}',' \\d{3}\\|\\d{8}',' [az]{3}\\|[az]{9}','Which of the following PCRE regular expressions best matches the string php|architect?\r\n','B');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (12,'md5()','sha1()','crc32()','crypt()','Which of the following functions can be used to determine the integrity of a string? \r\n','D');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (13,'The interpreter outputs a type mismatch error','The string is converted to a number and added to t','The string is discarded and the integer is preserv',' The integer and string are concatenated together ','What happens if you add a string to an integer using the + operator?\r\n','B');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (14,'strcmp()',' stricmp()','strcasecmp()','stristr()','The ___________ function can be used to compare two strings using a case-insensitive binary algorithm','C');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (15,'encode_hex()','pack()',' hex2bin()',' printf()','Which of the following functions can be used to convert the binary data stored in a string into its hexadecimal representation? \r\n','B');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (16,'play it again',' I','123','?','^[A-Za-z].* matches','A');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (17,'90001 and 90002-4323','9001 and 12-4321','8001 and 13-4321','7801 and 41-4325','^[0-9]{5}(\\-[0-9]{4})?$ matches','A');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (18,' Float, string','Positive number, negative number','Even number, string','Integer, string','Array values are keyed by ______ values (called indexed arrays) or using ______ values (called associative arrays). Of course, these key methods can be combined as well.','D');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (19,'78','19','NULL','0','What will the following script output?\r\n<?php\r\n$array = array (1, 2, 3, 5, 8, 13, 21, 34, 55);\r\n$sum = 0;\r\nfor ($i = 0; $i < 5; $i++) {\r\n$sum += $array[$array[$i]];\r\n}\r\necho $sum;\r\n?>\r\n','A');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (20,' 1 => \'b\'','True => \'a\', 1 => \'b\'','0 => \'a\', 1 => \'b\'','It will output NULL','What elements will the following script output?\r\n\r\n<?php\r\n$array = array (true => \'a\', 1 => \'b\');\r\nvar_dump ($array);\r\n?>\r\n','D');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (21,'array_key_exist()','array_key_exists()',' array_keys_exists()','arrays_key_exists()','Which array function checks if the specified key exists in the array\r\n','B');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (22,'Numeric array, String array, Multidimensional arra','Numeric array, Associative array, Dimensional arra','Numeric array, Associative array, Multidimensional','Const array, Associative array, Multidimensional a','There are three different kind of arrays:','C');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (23,'Yes, because the interpreter must always create a ','Yes, but only if the function modifies the content','No.','Yes, because PHP must monitor the execution of the','Absent any actual need for choosing one method over the other, does passing arrays by value to a read-only function reduce performance compared to passing them by reference?\r\n\r\n','C');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (24,' ksort()',' asort()',' krsort()','sort()','Assume you would like to sort an array in ascending order by value while preserving key associations. Which of the following PHP sorting functions would you use?\r\n','B');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (25,'array_diff',' diff_array ','arrays_diff','diff_arrays','What function computes the difference of arrays?\r\n','A');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (26,' count ','Sizeof','Array_Count','Count_array','What functions count elements in an array?\r\n','B');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (27,'An array with properties of that object as the arr','An array with properties of that array as the obje','An array with properties of that object as the Key',' An array with keys of that object as the array\'s ','What array will you get if you convert an object to an array?\r\n','A');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (28,' file_get_contents()',' fgets()',' fopen()','file()','Which of the following functions retrieve the entire contents of a file in such a way that it can be used as part of an expression? (Choose 2)\r\n\r\n','A');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (29,'While stat() works on open file pointers, fstat() ',' While fstat() works on open file pointers, stat()','fstat() has nothing to do with files ','stat() has nothing to do with files','What is the difference between stat() and fstat()?\r\n','B');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (30,'fgets()','file_get_contents()','file()',' readfile()','Which of the following functions does not read the entire contents of a file? ','A');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (31,'Returns the last accessed time of the file','Returns the first accessed time of the file','Strips of the path and returns the file name.','Strips of the path and returns the folder name.','What is the purpose of basename() function?\r\n','C');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (32,'As a broken image',' As a binary file for display within the browser','As a binary file for download','As a JPEG file for download','Assuming that image.jpg exists and is readable by PHP, how will the following script be displayed if called directly from a browser?\r\n\r\n<?php\r\nheader (\"Content-type: image/jpeg\");\r\n?>\r\n<?php\r\nreadfile (\"image.jpg\");\r\n?>\r\n','A');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (33,'Change the auto_detect_line_endings INI setting','Use a regular expression to detect the last letter','Use fpos()','Use ftok()','What should you do if your script is having problem recognizing file endings from a text file saved on a platform different from the one youíre reading it on?\r\n','A');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (34,'f_eof()',' f_of()','feofs()','feof()','The ............ function checks if the \"end-of-file\" (EOF) has been reached.\r\n','D');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (35,'fgetc()',' fgets()',' fget()','fgetf()','The ........... function is used to read a single character from a file.\r\n','A');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (36,' time()','date()',' strtotime()','gmmktime()','Which of the following functions do not return a timestamp? \r\n','B');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (37,'An integer','A floating-point number','An array',' A string','The getdate() function returns\r\n','C');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (38,'datesunrise()','date_sunrise()','date-sunrise()','date.sunrise()','.......... Returns the time of sunrise for a given day / location\r\n','B');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (39,'00:00:00','12:00:00','00:i:00','12:i:00','What will the following script output?\r\n\r\n<?php\r\n$time = strtotime (\'2004/01/01\');\r\necho date (\'H:\\i:s\', $time);\r\n?>','C');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (40,' check_date','verifydate',' Verify_date','checkdate','................Checks a date for numeric validity.\r\n','D');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (41,'It depends on the number of hours between the loca','There is no difference',' The two will only match if the local time zone is','The two will never match','What is the difference, in seconds, between the current timestamp in the GMT time zone and the current timestamp in your local time zone?\r\n','B');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (42,' date_default_timezone_set()','datedefault_timezone_set()','date_defaulttimezone_set()','date_default_timezoneset()','You must make a call to ................... to specify what time zone you want calculations to take place in before calling any date functions.\r\n','A');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (43,'It would output the number 0','It would output the number -1',' It would output the number 1','It would raise an error','What would happen if the following script were run on a Windows server set to Moscow, Russiaís time zone?\r\n<?php\r\necho gmmktime(0, 0, 0, 1, 1, 1970);\r\n?>\r\n\r\n','B');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (44,' mysqlconnect() function','mysql-connect() function','mysql_connect() function','sql_connect() function','In PHP in order to access MySQL database you will use:','C');
insert into `question_answer_php` (`question_id`,`option_one`,`option_two`,`option_three`,`option_four`,`question_desc`,`correct_option`) values (45,'The contents of OTHERTABLE will be deleted','The contents of both OTHERTABLE and MYTABLE will b','The contents of OTHERTABLE will be deleted, as wil','The database will remain unchanged.','What will happen at the end of the following sequence of SQL commands?\r\n\r\nBEGIN TRANSACTION\r\nDELETE FROM MYTABLE WHERE ID=1\r\nDELETE FROM OTHERTABLE\r\nROLLBACK TRANSACTION\r\n','D');

/*Table structure for table `registration` */

DROP TABLE IF EXISTS `registration`;

CREATE TABLE `registration` (
  `examinee_id` int(10) NOT NULL,
  `examinee_name` varchar(50) NOT NULL,
  `examinee_mobile` varchar(10) NOT NULL,
  `examinee_email` varchar(50) NOT NULL,
  `examiee_address` varchar(100) NOT NULL,
  `examiee_degree` varchar(50) NOT NULL,
  `examiee_exp` varchar(30) NOT NULL,
  `examiee_tech` varchar(5) default NULL,
  `examiee_reg_date` datetime default NULL,
  PRIMARY KEY  (`examinee_mobile`,`examinee_email`),
  KEY `examinee_id` (`examinee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `registration` */

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
